# config/config.yaml

storage:
  type: parquet
  directory: ./data/parquet

data_binding:
  driver: duckdb
  db_path: ./data/main.db

api:
  host: 0.0.0.0
  port: 8000

llm:
  provider: anthropic
  # The API key should be set as an environment variable, not here